version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devops
    ports:
      - "15432:5432" # 호스트와 컨테이너 간 포트 매핑
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
